<h1 style="text-align: center">
    Top 100 NFL Point Leaders for MHS <br><img src="img/MHSW 1.jpg" alt="MHS West" height="200" width="300"/>
</h1>
Leo idk why the list is above the table, i just copied it here for convenience. Also, why does "created by jake and leo" appear above the table?
ideally with this everything will be centered.

<table border="5" bordercolor="FFFFFF" style="text-align: center">
        <tr>
            <th>Rank</th>
            <th>Name</th>
            <th>Graduating Year</th>
            <th>Points</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Linda Pei</td>
            <td>2012</td>           
            <td>3750</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Jake Seaton</td>
            <td>2013</td>           
            <td>3087</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Mikaela Wefald</td>
            <td>2012</td>           
            <td>2832</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Lucy Liu</td>
            <td>2012</td>           
            <td>2627</td>
        </tr>
        <tr>
            <td>5</td>
            <td>Brodie Herrman</td>
            <td>2012</td>           
            <td>2235</td>
        </tr>
        <tr>
            <td>6</td>
            <td>Gihani Dissanayake</td>
            <td>2011</td>           
            <td>2029</td>
        </tr>
<tr>
            <td>7</td>
            <td>Procter	Sam</td>
            <td>2005</td>           
            <td>2028</td>
        </tr>
<tr>
            <td>8</td>
            <td>Fitch	Augie</td>
            <td>2012</td>           
            <td>2019</td>
        </tr>
<tr>
            <td>9</td>
            <td>Bolton 	Helen</td>
            <td>2008</td>           
            <td>2010</td>
        </tr>
<tr>
            <td>10</td>
            <td>Lin	Pat</td>
            <td>2008</td>           
            <td>1987</td>
        </tr>
<tr>
            <td>11</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>12</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>13</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>
<tr>
            <td>#</td>
            <td>Name</td>
            <td>Year</td>           
            <td>Points</td>
        </tr>




